default: &default
  adapter: <%= ENV.fetch("DB_ADAPTER", "mysql2") %>
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "rails") %>
  password: <%= ENV.fetch("DB_PASSWORD", "rails") %>
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DB_PORT", 3306) %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "mrd_edit_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_TEST_NAME", "mrd_edit_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "mrd_edit_production") %>
