source "https://rubygems.org"

gem "rails", "~> 8.1.4"
gem "mysql2", "~> 0.5"
gem "puma", ">= 5.0"

# Authentication & Security
gem "bcrypt", "~> 3.1.7"
gem "jwt", "~> 2.7"
gem "pundit", "~> 2.3"
gem "rack-cors"
gem "rack-attack"

# Environment Variables
gem "dotenv-rails", groups: [:development, :test]

# Pagination
gem "kaminari"

# Active Storage
gem "image_processing", "~> 1.2"
gem "bootsnap", require: false

# Platform
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "rspec-rails", "~> 7.0"
  gem "factory_bot_rails"
  gem "faker"
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
end

gem "googleauth", "~> 1.17"

gem "webmock", "~> 3.26", groups: [:development, :test]
